repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3.9
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pipenv run pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=./.pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
    - id: mypy 
      name: mypy 
      entry: pipenv run mypy
      language: system
      types: [python]
