name: pytest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pipenv
      run: pip install pipenv
    - name: Run tests
      run: |
        pipenv install --dev
        pipenv run pytest